// <auto-generated />
namespace ConsomiTounsi.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SecondMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202006061428359_SecondMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
